using System.Text;
using System.Text.Json;

namespace MxoHd.PacketResearch;

public static class ReportWriter
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true
    };

    public static void WriteJson(PacketResearchReport report, string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, JsonSerializer.Serialize(report, JsonOptions));
    }

    public static void WriteMarkdown(PacketResearchReport report, string path)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(path))!);
        File.WriteAllText(path, ToMarkdown(report));
    }

    public static string ToMarkdown(PacketResearchReport report)
    {
        StringBuilder builder = new();
        builder.AppendLine("# Packet Research Summary");
        builder.AppendLine();
        builder.AppendLine("Generated by `tools/PacketResearch`. This file summarizes packet evidence without copying raw dump bodies into the report.");
        builder.AppendLine();
        builder.AppendLine("## Inputs");
        builder.AppendLine();
        builder.AppendLine($"- Repository: `{report.RepositoryRoot}`");
        builder.AppendLine($"- Packet dump roots: {FormatList(report.PacketDumpRoots)}");
        builder.AppendLine($"- Rajko MxOEmu source: `{report.RajkoSourceRoot ?? "not provided"}`");
        builder.AppendLine($"- External source roots: {FormatList(report.ExternalSourceRoots)}");
        builder.AppendLine();

        int packetLines = report.PacketDumpFiles.Sum(file => file.PacketLikeLines);
        builder.AppendLine("## Totals");
        builder.AppendLine();
        builder.AppendLine($"- Local RPC headers: {report.LocalHeaders.Count}");
        builder.AppendLine($"- Local attribute definitions: {report.AttributeDefinitions.Count}");
        builder.AppendLine($"- Community FX definitions: {report.FxDefinitions.Count}");
        builder.AppendLine($"- Rajko RPC dispatch entries: {report.RajkoRpcHeaders.Count}");
        builder.AppendLine($"- Hardcoded command examples: {report.HardcodedCommands.Count}");
        builder.AppendLine($"- Hardcoded protocol 03 examples: {report.HardcodedProtocol03Examples.Count}");
        builder.AppendLine($"- External object-interaction command examples: {report.Protocol04InteractionCommandExamples.Count}");
        builder.AppendLine($"- Vendor inventory rows: {report.VendorInventoryEntries.Count}");
        builder.AppendLine($"- Protocol 04 interaction payloads: {report.PacketDumpFiles.Sum(file => file.Protocol04InteractionPayloads.Count)}");
        builder.AppendLine($"- Packet dump files with packet-like lines: {report.PacketDumpFiles.Count}");
        builder.AppendLine($"- Packet-like lines: {packetLines}");
        builder.AppendLine();

        AppendRajkoComparison(builder, report);
        AppendPacketDumpSummary(builder, report);
        AppendProtocol04InteractionSummary(builder, report);
        AppendProtocol04InteractionCommandExamples(builder, report);
        AppendVendorInventoryCorrelations(builder, report);
        AppendProtocol04SequenceSummary(builder, report);
        AppendProtocol03ObjectViewSummary(builder, report);
        AppendHardcodedProtocol03Examples(builder, report);
        AppendPlayerAttributePayloadSummary(builder, report);
        AppendManageBonusPayloadSummary(builder, report);
        AppendVendorSignals(builder, report);

        return builder.ToString();
    }

    private static void AppendRajkoComparison(StringBuilder builder, PacketResearchReport report)
    {
        if (report.RajkoComparisons.Count == 0)
        {
            builder.AppendLine("## Rajko RPC Dispatch Map");
            builder.AppendLine();
            builder.AppendLine("No Rajko source root was provided, so no external dispatch map was compared.");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("## Rajko RPC Dispatch Map");
        builder.AppendLine();
        builder.AppendLine("| External raw | Handler | Match | Local header | Local name |");
        builder.AppendLine("| --- | --- | --- | --- | --- |");
        foreach (RpcComparison comparison in report.RajkoComparisons)
        {
            builder.AppendLine(
                $"| `{comparison.External.RawHeader}` | `{comparison.External.Handler}` | {comparison.MatchKind} | `{comparison.Local?.EncodedHeader ?? "-"}` | {comparison.Local?.Name ?? "-"} |");
        }

        builder.AppendLine();
    }

    private static void AppendPacketDumpSummary(StringBuilder builder, PacketResearchReport report)
    {
        builder.AppendLine("## Packet Dump Coverage");
        builder.AppendLine();
        if (report.PacketDumpFiles.Count == 0)
        {
            builder.AppendLine("No packet dumps were parsed.");
            builder.AppendLine();
            return;
        }

        Dictionary<string, int> protocolTotals = new(StringComparer.OrdinalIgnoreCase);
        Dictionary<string, int> rpcTotals = new(StringComparer.OrdinalIgnoreCase);
        Dictionary<string, int> knownHeaderTotals = new(StringComparer.OrdinalIgnoreCase);
        foreach (PacketDumpFileSummary file in report.PacketDumpFiles)
        {
            AddCounts(protocolTotals, file.ProtocolCounts);
            AddCounts(rpcTotals, file.RpcHeaderCounts);
            AddCounts(knownHeaderTotals, file.KnownHeaderCounts);
        }

        builder.AppendLine("### Protocol Counts");
        builder.AppendLine();
        builder.AppendLine("| Protocol | Lines |");
        builder.AppendLine("| --- | ---: |");
        foreach ((string protocol, int count) in protocolTotals.OrderByDescending(entry => entry.Value))
        {
            builder.AppendLine($"| `{protocol}` | {count} |");
        }

        builder.AppendLine();
        builder.AppendLine("### Protocol 04 Header Hits");
        builder.AppendLine();
        if (rpcTotals.Count == 0)
        {
            builder.AppendLine("No protocol 04 headers were detected with the current heuristic.");
            builder.AppendLine();
        }
        else
        {
            builder.AppendLine("| Header | Count |");
            builder.AppendLine("| --- | ---: |");
            foreach ((string header, int count) in rpcTotals.OrderByDescending(entry => entry.Value).ThenBy(entry => entry.Key))
            {
                builder.AppendLine($"| `{header}` | {count} |");
            }

            builder.AppendLine();
        }

        builder.AppendLine("### Embedded Known Header Candidates");
        builder.AppendLine();
        builder.AppendLine("This scan searches every packet-like line for known two-byte local headers. Treat these as leads for manual decoding, not proof that the surrounding bytes are fully understood.");
        builder.AppendLine();
        if (knownHeaderTotals.Count == 0)
        {
            builder.AppendLine("No embedded known headers were detected.");
            builder.AppendLine();
        }
        else
        {
            builder.AppendLine("| Header | Count |");
            builder.AppendLine("| --- | ---: |");
            foreach ((string header, int count) in knownHeaderTotals.OrderByDescending(entry => entry.Value).ThenBy(entry => entry.Key).Take(30))
            {
                builder.AppendLine($"| `{header}` | {count} |");
            }

            builder.AppendLine();
        }

        builder.AppendLine("### Largest Parsed Files");
        builder.AppendLine();
        builder.AppendLine("| File | Packet-like lines | Protocol 04 hits | Embedded header candidates |");
        builder.AppendLine("| --- | ---: | ---: | ---: |");
        foreach (PacketDumpFileSummary file in report.PacketDumpFiles.OrderByDescending(file => file.PacketLikeLines).Take(15))
        {
            builder.AppendLine($"| `{file.File}` | {file.PacketLikeLines} | {file.RpcHeaderCounts.Values.Sum()} | {file.KnownHeaderCounts.Values.Sum()} |");
        }

        builder.AppendLine();
    }

    private static void AppendProtocol04InteractionSummary(StringBuilder builder, PacketResearchReport report)
    {
        Protocol04InteractionWithFile[] interactions = report.PacketDumpFiles
            .SelectMany(file => file.Protocol04InteractionPayloads.Select(payload => new Protocol04InteractionWithFile(file.File, payload)))
            .ToArray();

        if (interactions.Length == 0)
        {
            return;
        }

        builder.AppendLine("## Protocol 04 Object Interaction Payloads");
        builder.AppendLine();
        builder.AppendLine("This decodes the payload shape used by the local object-interaction handlers: four-byte object id, two-byte sector window from that id, and one-byte object type. Type names are local handler labels, so they are interaction leads rather than complete protocol semantics.");
        builder.AppendLine();
        builder.AppendLine("| Header | Kind | Object type | Local type label | Count | Distinct object ids | Sample | Sample payload |");
        builder.AppendLine("| --- | --- | ---: | --- | ---: | ---: | --- | --- |");
        foreach (var group in interactions
            .GroupBy(entry => new
            {
                entry.Payload.RawHeader,
                entry.Payload.InteractionKind,
                entry.Payload.ObjectType,
                entry.Payload.ObjectTypeName
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.RawHeader)
            .ThenBy(group => group.Key.ObjectType))
        {
            Protocol04InteractionWithFile sample = group.First();
            builder.AppendLine(
                $"| `{group.Key.RawHeader}` | {group.Key.InteractionKind} | {group.Key.ObjectType} | {group.Key.ObjectTypeName} | {group.Count()} | {group.Select(entry => entry.Payload.ObjectId).Distinct().Count()} | `{sample.File}:{sample.Payload.Line}` | `{sample.Payload.PayloadHex}` |");
        }

        builder.AppendLine();

        builder.AppendLine("### Repeated Interaction Object IDs");
        builder.AppendLine();
        builder.AppendLine("| Object id | Sector | Kind | Object type | Local type label | Count | Sample |");
        builder.AppendLine("| ---: | ---: | --- | ---: | --- | ---: | --- |");
        foreach (var group in interactions
            .GroupBy(entry => new
            {
                entry.Payload.ObjectId,
                entry.Payload.SectorId,
                entry.Payload.InteractionKind,
                entry.Payload.ObjectType,
                entry.Payload.ObjectTypeName
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.ObjectId)
            .Take(25))
        {
            Protocol04InteractionWithFile sample = group.First();
            builder.AppendLine(
                $"| {group.Key.ObjectId} | {group.Key.SectorId} | {group.Key.InteractionKind} | {group.Key.ObjectType} | {group.Key.ObjectTypeName} | {group.Count()} | `{sample.File}:{sample.Payload.Line}` |");
        }

        builder.AppendLine();
    }

    private static void AppendProtocol04InteractionCommandExamples(StringBuilder builder, PacketResearchReport report)
    {
        if (report.Protocol04InteractionCommandExamples.Count == 0)
        {
            return;
        }

        builder.AppendLine("## External Object Interaction Command Examples");
        builder.AppendLine();
        builder.AppendLine("These parse raw `HandleCommand:` debug lines from external MxOEmu source/log artifacts. They are not full packet captures, but they preserve client RPC command bytes that can validate object-interaction payload shape.");
        builder.AppendLine();
        builder.AppendLine("| Header | Kind | Object type | Local type label | Count | Distinct object ids | Sample | Sample payload |");
        builder.AppendLine("| --- | --- | ---: | --- | ---: | ---: | --- | --- |");
        foreach (var group in report.Protocol04InteractionCommandExamples
            .GroupBy(entry => new
            {
                entry.RawHeader,
                entry.InteractionKind,
                entry.ObjectType,
                entry.ObjectTypeName
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.RawHeader)
            .ThenBy(group => group.Key.ObjectType))
        {
            Protocol04InteractionCommandExample sample = group.First();
            builder.AppendLine(
                $"| `{group.Key.RawHeader}` | {group.Key.InteractionKind} | {group.Key.ObjectType} | {group.Key.ObjectTypeName} | {group.Count()} | {group.Select(entry => entry.ObjectId).Distinct().Count()} | `{sample.Source} {sample.File}:{sample.Line}` | `{sample.PayloadHex}` |");
        }

        builder.AppendLine();
        builder.AppendLine("### Repeated External Interaction Object IDs");
        builder.AppendLine();
        builder.AppendLine("| Object id | Sector | Kind | Object type | Local type label | Count | Sample |");
        builder.AppendLine("| ---: | ---: | --- | ---: | --- | ---: | --- |");
        foreach (var group in report.Protocol04InteractionCommandExamples
            .GroupBy(entry => new
            {
                entry.ObjectId,
                entry.SectorId,
                entry.InteractionKind,
                entry.ObjectType,
                entry.ObjectTypeName
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.ObjectId)
            .Take(25))
        {
            Protocol04InteractionCommandExample sample = group.First();
            builder.AppendLine(
                $"| {group.Key.ObjectId} | {group.Key.SectorId} | {group.Key.InteractionKind} | {group.Key.ObjectType} | {group.Key.ObjectTypeName} | {group.Count()} | `{sample.Source} {sample.File}:{sample.Line}` |");
        }

        builder.AppendLine();
    }

    private static void AppendVendorInventoryCorrelations(StringBuilder builder, PacketResearchReport report)
    {
        if (report.VendorInventoryEntries.Count == 0)
        {
            return;
        }

        Dictionary<uint, int> dumpInteractionCounts = report.PacketDumpFiles
            .SelectMany(file => file.Protocol04InteractionPayloads)
            .GroupBy(payload => payload.ObjectId)
            .ToDictionary(group => group.Key, group => group.Count());
        Dictionary<uint, int> externalCommandCounts = report.Protocol04InteractionCommandExamples
            .GroupBy(example => example.ObjectId)
            .ToDictionary(group => group.Key, group => group.Count());
        HashSet<uint> interactionObjectIds = new(dumpInteractionCounts.Keys.Concat(externalCommandCounts.Keys));
        VendorInventoryEntry[] matches = report.VendorInventoryEntries
            .Where(entry => interactionObjectIds.Contains(entry.VendorStaticId))
            .ToArray();
        if (matches.Length == 0)
        {
            return;
        }

        builder.AppendLine("## Vendor Inventory Object Correlations");
        builder.AppendLine();
        builder.AppendLine("This joins decoded object-interaction object ids against tracked `data/vendor_items.csv` rows. The vendor list was parser-derived from old logs and is incomplete, so a match is a lead that the static id may be vendor-related, not proof of a complete vendor exchange.");
        builder.AppendLine();
        builder.AppendLine("| Static object id | Metr ids | Vendor rows | Packet-dump interactions | External command interactions | Item counts | Sample items | Sample vendor row |");
        builder.AppendLine("| ---: | --- | ---: | ---: | ---: | --- | --- | --- |");
        foreach (var group in matches
            .GroupBy(entry => entry.VendorStaticId)
            .OrderByDescending(group => dumpInteractionCounts.GetValueOrDefault(group.Key) + externalCommandCounts.GetValueOrDefault(group.Key))
            .ThenBy(group => group.Key))
        {
            VendorInventoryEntry sample = group.First();
            string metrIds = string.Join(", ", group.Select(entry => entry.MetrId).Distinct().OrderBy(value => value));
            string itemCounts = string.Join(", ", group.Select(entry => entry.Items.Count).Distinct().OrderBy(value => value));
            string sampleItems = string.Join(", ", group.SelectMany(entry => entry.Items).Distinct().Take(8));
            builder.AppendLine(
                $"| {group.Key} | {metrIds} | {group.Count()} | {dumpInteractionCounts.GetValueOrDefault(group.Key)} | {externalCommandCounts.GetValueOrDefault(group.Key)} | {itemCounts} | `{sampleItems}` | `{sample.File}:{sample.Line}` |");
        }

        builder.AppendLine();
    }

    private static void AppendProtocol04SequenceSummary(StringBuilder builder, PacketResearchReport report)
    {
        var sequences = report.PacketDumpFiles
            .SelectMany(file => file.Protocol04PacketSequences.Select(sequence => new Protocol04SequenceWithFile(file.File, sequence)))
            .Where(entry => entry.Sequence.Direction != "client")
            .Where(entry => entry.Sequence.Headers.Any(header =>
                header.Equals("80 b2", StringComparison.OrdinalIgnoreCase)
                || header.Equals("80 bc", StringComparison.OrdinalIgnoreCase)))
            .ToArray();

        if (sequences.Length == 0)
        {
            return;
        }

        int bothCount = sequences.Count(entry =>
            entry.Sequence.Headers.Any(header => header.Equals("80 b2", StringComparison.OrdinalIgnoreCase))
            && entry.Sequence.Headers.Any(header => header.Equals("80 bc", StringComparison.OrdinalIgnoreCase)));

        builder.AppendLine("## Protocol 04 Server State Sequences");
        builder.AppendLine();
        builder.AppendLine("This groups top-level server protocol 04 packet header sequences that contain `80 b2` and/or `80 bc`. It preserves packet order so repeated state-bundle flows can be separated from isolated RPC hits.");
        builder.AppendLine();
        builder.AppendLine($"- State-related protocol 04 packets: {sequences.Length}");
        builder.AppendLine($"- Packets containing both `80 b2` and `80 bc`: {bothCount}");
        builder.AppendLine();
        builder.AppendLine("| Header sequence | Count | Contains `80 b2` | Contains `80 bc` | Sample |");
        builder.AppendLine("| --- | ---: | --- | --- | --- |");
        foreach (var group in sequences
            .GroupBy(entry => FormatSequence(entry.Sequence.Headers), StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key)
            .Take(25))
        {
            Protocol04SequenceWithFile sample = group.First();
            bool hasB2 = sample.Sequence.Headers.Any(header => header.Equals("80 b2", StringComparison.OrdinalIgnoreCase));
            bool hasBc = sample.Sequence.Headers.Any(header => header.Equals("80 bc", StringComparison.OrdinalIgnoreCase));
            builder.AppendLine(
                $"| `{group.Key}` | {group.Count()} | {FormatBoolean(hasB2)} | {FormatBoolean(hasBc)} | `{sample.File}:{sample.Sequence.Line}` |");
        }

        builder.AppendLine();
        AppendProtocol04StateFieldLinks(builder, report);
    }

    private static void AppendProtocol04StateFieldLinks(StringBuilder builder, PacketResearchReport report)
    {
        PlayerAttributePayloadWithFile[] b2Payloads = report.PacketDumpFiles
            .SelectMany(file => file.PlayerAttributePayloads.Select(payload => new PlayerAttributePayloadWithFile(file.File, payload)))
            .ToArray();
        PayloadWithFile[] bcPayloads = report.PacketDumpFiles
            .SelectMany(file => file.ManageBonusPayloads.Select(payload => new PayloadWithFile(file.File, payload)))
            .ToArray();

        var b2ByPacket = b2Payloads
            .GroupBy(entry => new PacketLocation(entry.File, entry.Payload.Line))
            .ToDictionary(group => group.Key, group => group.ToArray());
        var bcByPacket = bcPayloads
            .GroupBy(entry => new PacketLocation(entry.File, entry.Payload.Line))
            .ToDictionary(group => group.Key, group => group.ToArray());

        List<StateFieldLink> links = new();
        foreach ((PacketLocation packet, PlayerAttributePayloadWithFile[] b2Entries) in b2ByPacket)
        {
            if (!bcByPacket.TryGetValue(packet, out PayloadWithFile[]? bcEntries))
            {
                continue;
            }

            foreach (PlayerAttributePayloadWithFile b2 in b2Entries)
            {
                foreach (PayloadWithFile bc in bcEntries)
                {
                    if (b2.Payload.Field0Value != bc.Payload.Field1Value)
                    {
                        continue;
                    }

                    links.Add(new StateFieldLink(packet, b2, bc));
                }
            }
        }

        if (links.Count == 0)
        {
            return;
        }

        builder.AppendLine("### Cross-Family State Field Links");
        builder.AppendLine();
        builder.AppendLine("This links `80 b2` field 0 with `80 bc` field 1 when both values appear in the same top-level protocol 04 packet. These are high-priority semantic leads because they connect the short player-attribute/ability-load form to the longer manage-bonus form.");
        builder.AppendLine();
        builder.AppendLine("| Shared field | Packet count | Pair count | Sample | `80 b2` payload | `80 bc` payload |");
        builder.AppendLine("| --- | ---: | ---: | --- | --- | --- |");
        foreach (var group in links
            .GroupBy(link => new { link.B2.Payload.Field0Value, link.B2.Payload.Field0, link.Bc.Payload.Field1 })
            .OrderByDescending(group => group.Select(link => link.Packet).Distinct().Count())
            .ThenBy(group => group.Key.Field0Value)
            .Take(20))
        {
            StateFieldLink sample = group.First();
            int packetCount = group.Select(link => link.Packet).Distinct().Count();
            builder.AppendLine(
                $"| `{group.Key.Field0}` ({group.Key.Field0Value}) | {packetCount} | {group.Count()} | `{sample.Packet.File}:{sample.Packet.Line}` | `{sample.B2.Payload.PayloadHex}` | `{sample.Bc.Payload.PayloadHex}` |");
        }

        builder.AppendLine();
        AppendLinkedStateValueConsistency(builder, links);
    }

    private static void AppendLinkedStateValueConsistency(StringBuilder builder, IReadOnlyList<StateFieldLink> links)
    {
        var comparisons = links
            .Select(link => new LinkedStateValueComparison(
                link.Packet,
                link.B2.Payload.Field0,
                link.B2.Payload.Field1,
                PayloadWordAtByteOffset(link.Bc.Payload.PayloadHex, 9),
                PayloadWordAtByteOffset(link.Bc.Payload.PayloadHex, 11),
                link.B2.Payload.PayloadHex,
                link.Bc.Payload.PayloadHex))
            .ToArray();

        int repeatedFieldCount = comparisons.Count(comparison =>
            comparison.B2Field.Equals(comparison.BcByte9Field, StringComparison.OrdinalIgnoreCase));
        int matchingValueCount = comparisons.Count(comparison =>
            comparison.B2Value.Equals(comparison.BcByte11Value, StringComparison.OrdinalIgnoreCase));

        builder.AppendLine("### Linked Short/Long Field-Value Consistency");
        builder.AppendLine();
        builder.AppendLine("This compares each linked `80 b2` payload with the embedded field/value bytes inside its paired `80 bc` payload. In the dominant pattern, `80 bc` repeats the linked field at payload byte offset 9 and repeats the `80 b2` field 1 value at payload byte offset 11.");
        builder.AppendLine();
        builder.AppendLine($"- Same-packet field links: {comparisons.Length}");
        builder.AppendLine($"- Links with repeated `80 bc` byte 9 field: {repeatedFieldCount}");
        builder.AppendLine($"- Links with matching `80 bc` byte 11 value: {matchingValueCount}");
        builder.AppendLine();
        builder.AppendLine("| `80 b2` field | `80 b2` value | `80 bc` byte 9 field | `80 bc` byte 11 value | Pair count | Packet count | Sample |");
        builder.AppendLine("| --- | --- | --- | --- | ---: | ---: | --- |");
        foreach (var group in comparisons
            .GroupBy(comparison => new
            {
                comparison.B2Field,
                comparison.B2Value,
                comparison.BcByte9Field,
                comparison.BcByte11Value
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.B2Field, StringComparer.OrdinalIgnoreCase)
            .ThenBy(group => group.Key.B2Value, StringComparer.OrdinalIgnoreCase)
            .Take(20))
        {
            LinkedStateValueComparison sample = group.First();
            int packetCount = group.Select(comparison => comparison.Packet).Distinct().Count();
            builder.AppendLine(
                $"| `{group.Key.B2Field}` | `{group.Key.B2Value}` | `{group.Key.BcByte9Field}` | `{group.Key.BcByte11Value}` | {group.Count()} | {packetCount} | `{sample.Packet.File}:{sample.Packet.Line}` |");
        }

        builder.AppendLine();
    }

    private static void AppendProtocol03ObjectViewSummary(StringBuilder builder, PacketResearchReport report)
    {
        var samples = report.PacketDumpFiles
            .SelectMany(file => file.Protocol03ObjectViews.Select(sample => new Protocol03SampleWithFile(file.File, sample)))
            .ToArray();

        if (samples.Length == 0)
        {
            return;
        }

        builder.AppendLine("## Protocol 03 Object View Signatures");
        builder.AppendLine();
        builder.AppendLine("This decodes object-view updates in top-level protocol 03 packets using local `WorldPacket` framing, Rajko `MessageTypes.cpp` examples, and Rajko client movement parsing. It is intentionally conservative: classifications are packet-family labels, not full attribute decodes, and variable-length selectors stay marked as partial.");
        builder.AppendLine();
        int completeSamples = samples.Count(entry => entry.Sample.Complete);
        int knownSegments = samples.Sum(entry => entry.Sample.ParsedUpdateCount);
        int secondaryMovementWrappers = samples.Sum(entry => entry.Sample.Segments.Count(segment => segment.Classification == "secondary movement wrapper"));
        builder.AppendLine($"- Object messages parsed: {samples.Length}");
        builder.AppendLine($"- Fully segmented messages: {completeSamples}");
        builder.AppendLine($"- Known selector segments: {knownSegments}");
        builder.AppendLine($"- Secondary movement wrapper segments: {secondaryMovementWrappers}");
        builder.AppendLine();
        builder.AppendLine("| Classification | Update count | First selector | Count | Fully segmented | Sample | Prefix |");
        builder.AppendLine("| --- | ---: | --- | ---: | ---: | --- | --- |");
        foreach (var group in samples
            .GroupBy(entry => new
            {
                entry.Sample.Classification,
                entry.Sample.UpdateCount,
                entry.Sample.FirstSelector
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.Classification)
            .ThenBy(group => group.Key.UpdateCount)
            .Take(25))
        {
            var sample = group.First();
            builder.AppendLine(
                $"| {group.Key.Classification} | {group.Key.UpdateCount} | `{group.Key.FirstSelector}` | {group.Count()} | {group.Count(entry => entry.Sample.Complete)} | `{sample.File}:{sample.Sample.Line}` | `{sample.Sample.PrefixHex}` |");
        }

        builder.AppendLine();
        builder.AppendLine("### Protocol 03 Selector Sizes");
        builder.AppendLine();
        builder.AppendLine("| Selector | Segment classification | Payload/tail bytes | Known length | Count | Sample | Payload prefix |");
        builder.AppendLine("| --- | --- | ---: | --- | ---: | --- | --- |");
        foreach (var group in samples
            .SelectMany(entry => entry.Sample.Segments.Select(segment => new Protocol03SegmentWithFile(entry.File, entry.Sample.Line, segment)))
            .GroupBy(entry => new
            {
                entry.Segment.Selector,
                entry.Segment.Classification,
                entry.Segment.PayloadBytes,
                entry.Segment.IsKnownLength
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.Selector, StringComparer.OrdinalIgnoreCase)
            .Take(25))
        {
            Protocol03SegmentWithFile sample = group
                .OrderByDescending(entry => entry.Segment.PayloadPrefixHex.Length > 0)
                .First();
            string knownLength = group.Key.IsKnownLength ? "yes" : "no";
            builder.AppendLine(
                $"| `{group.Key.Selector}` | {group.Key.Classification} | {group.Key.PayloadBytes} | {knownLength} | {group.Count()} | `{sample.File}:{sample.Line}` | `{sample.Segment.PayloadPrefixHex}` |");
        }

        builder.AppendLine();
        builder.AppendLine("### Protocol 03 Files");
        builder.AppendLine();
        builder.AppendLine("| File | Parsed object-view packets | Fully segmented | Top classification |");
        builder.AppendLine("| --- | ---: | ---: | --- |");
        foreach (var fileGroup in samples
            .GroupBy(entry => entry.File, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key)
            .Take(15))
        {
            var topClassification = fileGroup
                .GroupBy(entry => entry.Sample.Classification)
                .OrderByDescending(group => group.Count())
                .ThenBy(group => group.Key)
                .First();
            builder.AppendLine($"| `{fileGroup.Key}` | {fileGroup.Count()} | {fileGroup.Count(entry => entry.Sample.Complete)} | {topClassification.Key} ({topClassification.Count()}) |");
        }

        builder.AppendLine();
    }

    private static void AppendHardcodedProtocol03Examples(StringBuilder builder, PacketResearchReport report)
    {
        Protocol03HardcodedExample[] examples = report.HardcodedProtocol03Examples
            .OrderBy(example => example.Source)
            .ThenBy(example => example.File, StringComparer.OrdinalIgnoreCase)
            .ThenBy(example => example.Line)
            .ToArray();

        if (examples.Length == 0)
        {
            return;
        }

        builder.AppendLine("## Hardcoded Protocol 03 Examples");
        builder.AppendLine();
        builder.AppendLine("This mines local and external hardcoded object-message constants, including Rajko/TasteeWheat `HexGenericMsg` examples and local `hexStringToBytes` object messages. These examples are provenance hints for protocol 03 layouts, not proof of live-client captures.");
        builder.AppendLine();
        builder.AppendLine("| Source | Location | Payload bytes | Object messages | Fully segmented | Top classification | Prefix |");
        builder.AppendLine("| --- | --- | ---: | ---: | ---: | --- | --- |");
        foreach (Protocol03HardcodedExample example in examples.Take(40))
        {
            var topClassification = example.ObjectViews
                .GroupBy(sample => sample.Classification)
                .OrderByDescending(group => group.Count())
                .ThenBy(group => group.Key)
                .First();
            builder.AppendLine(
                $"| {example.Source} | `{FormatSourceLocation(example.File, example.Line)}` | {example.PayloadLength} | {example.ObjectViews.Count} | {example.ObjectViews.Count(sample => sample.Complete)} | {topClassification.Key} ({topClassification.Count()}) | `{example.PrefixHex}` |");
        }

        builder.AppendLine();
    }

    private static void AppendPlayerAttributePayloadSummary(StringBuilder builder, PacketResearchReport report)
    {
        var payloads = report.PacketDumpFiles
            .SelectMany(file => file.PlayerAttributePayloads.Select(payload => new PlayerAttributePayloadWithFile(file.File, payload)))
            .ToArray();

        HardcodedCommandExample[] hardcoded = report.HardcodedCommands
            .Where(command => command.RawHeader.Equals("80 b2", StringComparison.OrdinalIgnoreCase))
            .OrderBy(command => command.Source)
            .ThenBy(command => command.File, StringComparer.OrdinalIgnoreCase)
            .ThenBy(command => command.Line)
            .ToArray();

        if (payloads.Length == 0 && hardcoded.Length == 0)
        {
            return;
        }

        builder.AppendLine("## SERVER_PLAYER_ATTRIBUTE / SERVER_ABILITY_LOAD Payload Groups");
        builder.AppendLine();
        builder.AppendLine("The local protocol map aliases `80 b2` as both `SERVER_PLAYER_ATTRIBUTE` and `SERVER_ABILITY_LOAD`, so this section treats it as an ambiguous server attribute/ability-load family until paired client actions prove the semantics.");
        builder.AppendLine();

        if (payloads.Length > 0)
        {
            builder.AppendLine("| Payload bytes | Field 0 | Field 1 | Field 2 | Count | Sample | Sample payload |");
            builder.AppendLine("| ---: | --- | --- | --- | ---: | --- | --- |");
            foreach (var group in payloads
                .GroupBy(entry => new
                {
                    entry.Payload.PayloadLength,
                    entry.Payload.Field0,
                    entry.Payload.Field1,
                    entry.Payload.Field2
                })
                .OrderByDescending(group => group.Count())
                .ThenBy(group => group.Key.PayloadLength)
                .ThenBy(group => group.Key.Field0)
                .ThenBy(group => group.Key.Field1)
                .Take(25))
            {
                PlayerAttributePayloadWithFile sample = group.First();
                builder.AppendLine(
                    $"| {group.Key.PayloadLength} | `{group.Key.Field0}` | `{group.Key.Field1}` | `{group.Key.Field2}` | {group.Count()} | `{sample.File}:{sample.Payload.Line}` | `{sample.Payload.PayloadHex}` |");
            }

            builder.AppendLine();
        }

        AppendPlayerAttributeHardcodedExamples(builder, payloads, hardcoded);
        AppendPlayerAttributeIndexCandidates(builder, report, payloads);
    }

    private static void AppendPlayerAttributeHardcodedExamples(
        StringBuilder builder,
        IReadOnlyList<PlayerAttributePayloadWithFile> payloads,
        IReadOnlyList<HardcodedCommandExample> hardcoded)
    {
        if (hardcoded.Count == 0)
        {
            return;
        }

        Dictionary<string, int> exactCounts = payloads
            .GroupBy(entry => entry.Payload.PayloadHex)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.OrdinalIgnoreCase);
        Dictionary<string, int> exactHardcodedCounts = hardcoded
            .GroupBy(example => example.PayloadHex)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.OrdinalIgnoreCase);

        builder.AppendLine("### Hardcoded `80 b2` Examples");
        builder.AppendLine();
        builder.AppendLine("| Source | Location | Field 0 | Field 1 | Field 2 | Exact corpus hits | Field-group hits | Same hardcoded payloads | Payload |");
        builder.AppendLine("| --- | --- | --- | --- | --- | ---: | ---: | ---: | --- |");
        foreach (HardcodedCommandExample example in hardcoded)
        {
            int fieldGroupHits = payloads.Count(entry =>
                entry.Payload.PayloadLength == example.PayloadLength
                && entry.Payload.Field0.Equals(example.Field0, StringComparison.OrdinalIgnoreCase)
                && entry.Payload.Field1.Equals(example.Field1, StringComparison.OrdinalIgnoreCase)
                && entry.Payload.Field2.Equals(example.Field2, StringComparison.OrdinalIgnoreCase));
            exactCounts.TryGetValue(example.PayloadHex, out int exactHits);
            exactHardcodedCounts.TryGetValue(example.PayloadHex, out int sameHardcodedPayloads);
            builder.AppendLine(
                $"| {example.Source} | `{FormatSourceLocation(example.File, example.Line)}` | `{example.Field0}` | `{example.Field1}` | `{example.Field2}` | {exactHits} | {fieldGroupHits} | {sameHardcodedPayloads} | `{example.PayloadHex}` |");
        }

        builder.AppendLine();
    }

    private static void AppendPlayerAttributeIndexCandidates(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PlayerAttributePayloadWithFile> payloads)
    {
        if (payloads.Count == 0)
        {
            return;
        }

        var groups = payloads
            .GroupBy(entry => (int)entry.Payload.Field0Value)
            .Select(group => new
            {
                Field0Value = group.Key,
                Count = group.Count(),
                CreationCandidates = AttributeCandidates(report.AttributeDefinitions, group.Key, creationIndex: true),
                UpdateCandidates = AttributeCandidates(report.AttributeDefinitions, group.Key, creationIndex: false)
            })
            .Where(group => group.CreationCandidates.Length > 0 || group.UpdateCandidates.Length > 0)
            .OrderByDescending(group => group.Count)
            .ThenBy(group => group.Field0Value)
            .Take(20)
            .ToArray();

        if (groups.Length == 0)
        {
            return;
        }

        builder.AppendLine("### Candidate `80 b2` Attribute Index Matches");
        builder.AppendLine();
        builder.AppendLine("This treats field 0 as a little-endian 16-bit attribute index and compares it with local gameobject attribute creation/update indices. These are candidate labels, not proof of the field's meaning.");
        builder.AppendLine();
        builder.AppendLine("| Field 0 | Count | Creation-index candidates | Update-index candidates |");
        builder.AppendLine("| ---: | ---: | --- | --- |");
        foreach (var group in groups)
        {
            builder.AppendLine(
                $"| {group.Field0Value} | {group.Count} | {FormatCandidateList(group.CreationCandidates)} | {FormatCandidateList(group.UpdateCandidates)} |");
        }

        builder.AppendLine();
    }

    private static void AppendManageBonusPayloadSummary(StringBuilder builder, PacketResearchReport report)
    {
        var payloads = report.PacketDumpFiles
            .SelectMany(file => file.ManageBonusPayloads.Select(payload => new PayloadWithFile(file.File, payload)))
            .ToArray();

        if (payloads.Length == 0)
        {
            return;
        }

        builder.AppendLine("## SERVER_MANAGE_BONUS Payload Groups");
        builder.AppendLine();
        builder.AppendLine("This groups top-level protocol 04 `80 bc` payloads by payload length and first three two-byte fields. Use this to separate embedded header-looking bytes from ordinary payload fields.");
        builder.AppendLine();
        builder.AppendLine("| Payload bytes | Field 0 | Field 1 | Field 2 | Count | Sample | Sample payload |");
        builder.AppendLine("| ---: | --- | --- | --- | ---: | --- | --- |");
        foreach (var group in payloads
            .GroupBy(entry => new
            {
                entry.Payload.PayloadLength,
                entry.Payload.Field0,
                entry.Payload.Field1,
                entry.Payload.Field2
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.PayloadLength)
            .ThenBy(group => group.Key.Field0)
            .ThenBy(group => group.Key.Field1)
            .Take(25))
        {
            var sample = group.First();
            builder.AppendLine(
                $"| {group.Key.PayloadLength} | `{group.Key.Field0}` | `{group.Key.Field1}` | `{group.Key.Field2}` | {group.Count()} | `{sample.File}:{sample.Payload.Line}` | `{sample.Payload.PayloadHex}` |");
        }

        builder.AppendLine();

        AppendManageBonusFieldLayoutSummary(builder, payloads);
        AppendHardcodedManageBonusFamilyCoverage(builder, report, payloads);
        AppendHardcodedManageBonusExamples(builder, report, payloads);
        AppendManageBonusAttributeCandidates(builder, report, payloads);
        AppendManageBonusInteractionAttributeCandidates(builder, report, payloads);
        AppendManageBonusFxCandidates(builder, report, payloads);

        var vendorOpenCandidates = payloads
            .Where(entry => entry.Payload.PayloadHex.Contains("81 0d", StringComparison.OrdinalIgnoreCase))
            .ToArray();
        if (vendorOpenCandidates.Length == 0)
        {
            return;
        }

        builder.AppendLine("### `80 bc` Payloads Containing `81 0d`");
        builder.AppendLine();
        builder.AppendLine("These are top-level `80 bc` payloads that contain bytes matching `SERVER_VENDOR_OPEN`. In the current corpus they appear as payload fields, not parsed protocol 04 headers.");
        builder.AppendLine();
        builder.AppendLine("| File | Line | Field 0 | Field 1 | Field 2 | Payload |");
        builder.AppendLine("| --- | ---: | --- | --- | --- | --- |");
        foreach (var entry in vendorOpenCandidates.Take(10))
        {
            builder.AppendLine(
                $"| `{entry.File}` | {entry.Payload.Line} | `{entry.Payload.Field0}` | `{entry.Payload.Field1}` | `{entry.Payload.Field2}` | `{entry.Payload.PayloadHex}` |");
        }

        builder.AppendLine();
    }

    private static void AppendManageBonusFieldLayoutSummary(
        StringBuilder builder,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        ManageBonusLayout[] layouts = payloads
            .Select(entry => new ManageBonusLayout(
                entry.File,
                entry.Payload.Line,
                entry.Payload.Field0,
                entry.Payload.Field1,
                entry.Payload.Field2,
                PayloadWordAtByteOffset(entry.Payload.PayloadHex, 9),
                PayloadWordAtByteOffset(entry.Payload.PayloadHex, 11),
                PayloadWordAtByteOffset(entry.Payload.PayloadHex, 15),
                entry.Payload.PayloadHex))
            .ToArray();

        if (layouts.Length == 0)
        {
            return;
        }

        builder.AppendLine("### `80 bc` Field Layout by Leading Field");
        builder.AppendLine();
        builder.AppendLine("This groups `80 bc` payloads by field 0 and compares field 1 / field 2 with later two-byte windows inside the same 20-byte payload. It is a layout analysis, not a semantic decode.");
        builder.AppendLine();
        builder.AppendLine("| Field 0 | Count | Field 1 repeated at byte 9 | Field 2 repeated at byte 11 | Dominant byte 9 / byte 11 / byte 15 layout | Layout count | Sample |");
        builder.AppendLine("| --- | ---: | ---: | ---: | --- | ---: | --- |");
        foreach (var group in layouts
            .GroupBy(layout => layout.Field0, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key, StringComparer.OrdinalIgnoreCase)
            .Take(20))
        {
            var dominantLayout = group
                .GroupBy(layout => new
                {
                    layout.Byte9Field,
                    layout.Byte11Value,
                    layout.Byte15Value
                })
                .OrderByDescending(layoutGroup => layoutGroup.Count())
                .ThenBy(layoutGroup => layoutGroup.Key.Byte9Field, StringComparer.OrdinalIgnoreCase)
                .First();
            ManageBonusLayout sample = dominantLayout.First();
            int repeatedFieldCount = group.Count(layout =>
                layout.Field1.Equals(layout.Byte9Field, StringComparison.OrdinalIgnoreCase));
            int repeatedField2Count = group.Count(layout =>
                layout.Field2.Equals(layout.Byte11Value, StringComparison.OrdinalIgnoreCase));
            builder.AppendLine(
                $"| `{group.Key}` | {group.Count()} | {repeatedFieldCount} | {repeatedField2Count} | `{dominantLayout.Key.Byte9Field}` / `{dominantLayout.Key.Byte11Value}` / `{dominantLayout.Key.Byte15Value}` | {dominantLayout.Count()} | `{sample.File}:{sample.Line}` |");
        }

        builder.AppendLine();
    }

    private static void AppendHardcodedManageBonusFamilyCoverage(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        HardcodedCommandExample[] examples = report.HardcodedCommands
            .Where(command => command.RawHeader.Equals("80 bc", StringComparison.OrdinalIgnoreCase))
            .ToArray();
        if (examples.Length == 0)
        {
            return;
        }

        Dictionary<string, PayloadWithFile[]> payloadsByField0 = payloads
            .GroupBy(entry => entry.Payload.Field0, StringComparer.OrdinalIgnoreCase)
            .ToDictionary(group => group.Key, group => group.ToArray(), StringComparer.OrdinalIgnoreCase);

        builder.AppendLine("### Hardcoded `80 bc` Family Coverage");
        builder.AppendLine();
        builder.AppendLine("This groups manual `80 bc` constants by field 0 and compares each family with corpus payloads. It shows which old hardcoded families have corpus backing at the field-group level and which still only have local provenance.");
        builder.AppendLine();
        builder.AppendLine("| Field 0 | Corpus family payloads | Hardcoded examples | Matched hardcoded field groups | Total field-group corpus hits | Best field-group corpus hits | Dominant corpus byte 9 / byte 11 / byte 15 layout | Example sources |");
        builder.AppendLine("| --- | ---: | ---: | ---: | ---: | ---: | --- | --- |");
        foreach (var group in examples
            .GroupBy(example => example.Field0, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(group => payloadsByField0.TryGetValue(group.Key, out PayloadWithFile[]? family) ? family.Length : 0)
            .ThenBy(group => group.Key, StringComparer.OrdinalIgnoreCase))
        {
            payloadsByField0.TryGetValue(group.Key, out PayloadWithFile[]? familyPayloads);
            familyPayloads ??= Array.Empty<PayloadWithFile>();
            int[] fieldGroupHits = group
                .GroupBy(example => new
                {
                    example.PayloadLength,
                    example.Field0,
                    example.Field1,
                    example.Field2
                })
                .Select(fieldGroup => familyPayloads.Count(entry =>
                    entry.Payload.PayloadLength == fieldGroup.Key.PayloadLength
                    && entry.Payload.Field0.Equals(fieldGroup.Key.Field0, StringComparison.OrdinalIgnoreCase)
                    && entry.Payload.Field1.Equals(fieldGroup.Key.Field1, StringComparison.OrdinalIgnoreCase)
                    && entry.Payload.Field2.Equals(fieldGroup.Key.Field2, StringComparison.OrdinalIgnoreCase)))
                .ToArray();
            int matchedFieldGroups = fieldGroupHits.Count(count => count > 0);
            int totalFieldGroupHits = fieldGroupHits.Sum();
            int bestFieldGroupHits = fieldGroupHits.Length == 0 ? 0 : fieldGroupHits.Max();
            string dominantLayout = FormatDominantManageBonusLayout(familyPayloads);
            string sources = FormatCandidateList(group
                .OrderBy(example => example.Source, StringComparer.OrdinalIgnoreCase)
                .ThenBy(example => example.File, StringComparer.OrdinalIgnoreCase)
                .ThenBy(example => example.Line)
                .Take(5)
                .Select(example => $"{example.Source} {FormatSourceLocation(example.File, example.Line)}")
                .ToArray());

            builder.AppendLine(
                $"| `{group.Key}` | {familyPayloads.Length} | {group.Count()} | {matchedFieldGroups} | {totalFieldGroupHits} | {bestFieldGroupHits} | {dominantLayout} | {sources} |");
        }

        builder.AppendLine();
    }

    private static void AppendHardcodedManageBonusExamples(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        HardcodedCommandExample[] examples = report.HardcodedCommands
            .Where(command => command.RawHeader.Equals("80 bc", StringComparison.OrdinalIgnoreCase))
            .OrderBy(command => command.Source)
            .ThenBy(command => command.File, StringComparer.OrdinalIgnoreCase)
            .ThenBy(command => command.Line)
            .ToArray();

        if (examples.Length == 0)
        {
            return;
        }

        Dictionary<string, int> exactCounts = payloads
            .GroupBy(entry => entry.Payload.PayloadHex)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.OrdinalIgnoreCase);
        Dictionary<string, int> exactHardcodedCounts = examples
            .GroupBy(example => example.PayloadHex)
            .ToDictionary(group => group.Key, group => group.Count(), StringComparer.OrdinalIgnoreCase);

        builder.AppendLine("### Hardcoded `80 bc` Examples");
        builder.AppendLine();
        builder.AppendLine("This compares Rajko `HexGenericMsg` examples and local queued `hexStringToBytes` RPC constants, including commented examples, against the imported dump corpus. It highlights which manual packet constants are backed by corpus field groups and which still need provenance.");
        builder.AppendLine();
        builder.AppendLine("| Source | Location | Field 0 | Field 1 | Field 2 | Exact corpus hits | Field-group hits | Same hardcoded payloads | Payload |");
        builder.AppendLine("| --- | --- | --- | --- | --- | ---: | ---: | ---: | --- |");
        foreach (HardcodedCommandExample example in examples.Take(40))
        {
            int fieldGroupHits = payloads.Count(entry =>
                entry.Payload.PayloadLength == example.PayloadLength
                && entry.Payload.Field0.Equals(example.Field0, StringComparison.OrdinalIgnoreCase)
                && entry.Payload.Field1.Equals(example.Field1, StringComparison.OrdinalIgnoreCase)
                && entry.Payload.Field2.Equals(example.Field2, StringComparison.OrdinalIgnoreCase));
            exactCounts.TryGetValue(example.PayloadHex, out int exactHits);
            exactHardcodedCounts.TryGetValue(example.PayloadHex, out int sameHardcodedPayloads);
            builder.AppendLine(
                $"| {example.Source} | `{FormatSourceLocation(example.File, example.Line)}` | `{example.Field0}` | `{example.Field1}` | `{example.Field2}` | {exactHits} | {fieldGroupHits} | {sameHardcodedPayloads} | `{example.PayloadHex}` |");
        }

        builder.AppendLine();
    }

    private static void AppendManageBonusAttributeCandidates(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        var groups = payloads
            .GroupBy(entry => (int)entry.Payload.Field1Value)
            .Select(group => new
            {
                Field1Value = group.Key,
                Count = group.Count(),
                CreationCandidates = AttributeCandidates(report.AttributeDefinitions, group.Key, creationIndex: true),
                UpdateCandidates = AttributeCandidates(report.AttributeDefinitions, group.Key, creationIndex: false)
            })
            .Where(group => group.CreationCandidates.Length > 0 || group.UpdateCandidates.Length > 0)
            .OrderByDescending(group => group.Count)
            .ThenBy(group => group.Field1Value)
            .Take(20)
            .ToArray();

        if (groups.Length == 0)
        {
            return;
        }

        builder.AppendLine("### Candidate Attribute Index Matches");
        builder.AppendLine();
        builder.AppendLine("This treats field 1 as a little-endian 16-bit index and compares it with local gameobject attribute creation/update indices. These are candidate labels, not proof of the field's meaning.");
        builder.AppendLine();
        builder.AppendLine("| Field 1 | Count | Creation-index candidates | Update-index candidates |");
        builder.AppendLine("| ---: | ---: | --- | --- |");
        foreach (var group in groups)
        {
            builder.AppendLine(
                $"| {group.Field1Value} | {group.Count} | {FormatCandidateList(group.CreationCandidates)} | {FormatCandidateList(group.UpdateCandidates)} |");
        }

        builder.AppendLine();
    }

    private static void AppendManageBonusFxCandidates(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        if (report.FxDefinitions.Count == 0)
        {
            return;
        }

        Dictionary<string, FxDefinition> fxByHex = new(StringComparer.OrdinalIgnoreCase);
        foreach (FxDefinition fx in report.FxDefinitions)
        {
            fxByHex.TryAdd(fx.LittleEndianHex, fx);
            fxByHex.TryAdd(fx.BigEndianHex, fx);
        }

        var matches = payloads
            .SelectMany(entry => FindFxMatches(entry.File, entry.Payload, fxByHex))
            .GroupBy(match => new { match.Offset, match.Hex, match.Name })
            .Select(group => new
            {
                group.Key.Offset,
                group.Key.Hex,
                group.Key.Name,
                Count = group.Count(),
                Sample = group.First()
            })
            .OrderByDescending(group => group.Count)
            .ThenBy(group => group.Offset)
            .ThenBy(group => group.Hex)
            .Take(20)
            .ToArray();

        if (matches.Length == 0)
        {
            return;
        }

        builder.AppendLine("### Candidate FX ID Matches");
        builder.AppendLine();
        builder.AppendLine("This scans each `80 bc` payload for four-byte windows that match imported `fxlisthex.txt` IDs. Some hits may be coincidental, but repeated matches are useful leads for effect-bearing fields.");
        builder.AppendLine();
        builder.AppendLine("| Offset | FX hex | FX name | Count | Sample | Sample payload |");
        builder.AppendLine("| ---: | --- | --- | ---: | --- | --- |");
        foreach (var match in matches)
        {
            builder.AppendLine(
                $"| {match.Offset} | `{match.Hex}` | {match.Name} | {match.Count} | `{match.Sample.File}:{match.Sample.Line}` | `{match.Sample.PayloadHex}` |");
        }

        builder.AppendLine();
    }

    private static void AppendManageBonusInteractionAttributeCandidates(
        StringBuilder builder,
        PacketResearchReport report,
        IReadOnlyList<PayloadWithFile> payloads)
    {
        Dictionary<int, int> payloadCountsByField = payloads
            .GroupBy(entry => (int)entry.Payload.Field1Value)
            .ToDictionary(group => group.Key, group => group.Count());

        var candidates = report.AttributeDefinitions
            .SelectMany(attribute => new[]
            {
                new AttributeCandidateHit(attribute.CreationIndex, "creation", attribute),
                new AttributeCandidateHit(attribute.UpdateIndex, "update", attribute)
            })
            .Where(hit => payloadCountsByField.ContainsKey(hit.FieldValue))
            .Where(hit => IsInteractionAttributeName(hit.Attribute.AttributeName))
            .GroupBy(hit => new
            {
                hit.FieldValue,
                hit.IndexKind,
                hit.Attribute.AttributeName
            })
            .Select(group => new
            {
                group.Key.FieldValue,
                PayloadCount = payloadCountsByField[group.Key.FieldValue],
                group.Key.IndexKind,
                group.Key.AttributeName,
                DefinitionCount = group.Count(),
                Classes = group
                    .Select(hit => hit.Attribute.ClassId is int classId
                        ? $"{hit.Attribute.ClassName} ({classId})"
                        : hit.Attribute.ClassName)
                    .Distinct(StringComparer.OrdinalIgnoreCase)
                    .OrderBy(value => value)
                    .Take(5)
                    .ToArray()
            })
            .OrderByDescending(candidate => candidate.PayloadCount)
            .ThenBy(candidate => candidate.FieldValue)
            .ThenBy(candidate => candidate.AttributeName)
            .Take(25)
            .ToArray();

        if (candidates.Length == 0)
        {
            return;
        }

        builder.AppendLine("### Vendor and Interaction Attribute Leads");
        builder.AppendLine();
        builder.AppendLine("This narrows the candidate attribute-index table to names that look relevant to vendor, NPC, inventory, trade, loot, or object interaction workflows. These are priority leads for paired packet captures, not decoded field names.");
        builder.AppendLine();
        builder.AppendLine("| Field 1 | Count | Index kind | Attribute | Definitions | Example classes |");
        builder.AppendLine("| ---: | ---: | --- | --- | ---: | --- |");
        foreach (var candidate in candidates)
        {
            builder.AppendLine(
                $"| {candidate.FieldValue} | {candidate.PayloadCount} | {candidate.IndexKind} | {candidate.AttributeName} | {candidate.DefinitionCount} | {FormatCandidateList(candidate.Classes)} |");
        }

        builder.AppendLine();
    }

    private static void AppendVendorSignals(StringBuilder builder, PacketResearchReport report)
    {
        builder.AppendLine("## Vendor Packet Signals");
        builder.AppendLine();
        RpcHeaderEntry[] vendorHeaders = report.LocalHeaders
            .Where(entry => entry.Name.Contains("VENDOR", StringComparison.OrdinalIgnoreCase))
            .OrderBy(entry => entry.Direction)
            .ThenBy(entry => entry.Name)
            .ToArray();

        if (vendorHeaders.Length == 0)
        {
            builder.AppendLine("No local vendor headers were found.");
            builder.AppendLine();
            return;
        }

        builder.AppendLine("| Protocol | Local name | Direction | Value | Encoded header | Embedded candidate hits | Sample files |");
        builder.AppendLine("| --- | --- | --- | ---: | --- | ---: | --- |");
        foreach (RpcHeaderEntry header in vendorHeaders)
        {
            int hits = report.PacketDumpFiles
                .SelectMany(file => file.KnownHeaderCounts)
                .Where(entry => IsHeaderLabelMatch(entry.Key, header))
                .Sum(entry => entry.Value);
            builder.AppendLine($"| {header.Protocol} | {header.Name} | {header.Direction} | `{header.Value:x}` | `{header.EncodedHeader}` | {hits} | {FormatHeaderSamples(report.PacketDumpFiles, header)} |");
        }

        builder.AppendLine();
    }

    private static void AddCounts(Dictionary<string, int> totals, IReadOnlyDictionary<string, int> counts)
    {
        foreach ((string key, int value) in counts)
        {
            totals[key] = totals.TryGetValue(key, out int existing) ? existing + value : value;
        }
    }

    private static bool IsHeaderLabelMatch(string label, RpcHeaderEntry header)
    {
        return label.StartsWith(header.EncodedHeader + " ", StringComparison.OrdinalIgnoreCase)
            && label.Contains(header.Name, StringComparison.OrdinalIgnoreCase)
            && label.Contains($"[{header.Protocol} {header.Direction}]", StringComparison.OrdinalIgnoreCase);
    }

    private static string FormatHeaderSamples(IReadOnlyList<PacketDumpFileSummary> files, RpcHeaderEntry header)
    {
        List<string> samples = new();
        foreach (PacketDumpFileSummary file in files)
        {
            foreach ((string label, IReadOnlyList<int> lines) in file.KnownHeaderSampleLines)
            {
                if (!IsHeaderLabelMatch(label, header))
                {
                    continue;
                }

                samples.Add($"`{file.File}:{string.Join(",", lines.Take(3))}`");
                if (samples.Count == 3)
                {
                    return string.Join("<br>", samples);
                }
            }
        }

        return samples.Count == 0 ? "-" : string.Join("<br>", samples);
    }

    private static string[] AttributeCandidates(
        IReadOnlyList<AttributeDefinition> attributes,
        int fieldValue,
        bool creationIndex)
    {
        return attributes
            .Where(attribute => creationIndex ? attribute.CreationIndex == fieldValue : attribute.UpdateIndex == fieldValue)
            .GroupBy(attribute => attribute.AttributeName, StringComparer.OrdinalIgnoreCase)
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key)
            .Take(8)
            .Select(group => $"{group.Key} ({group.Count()})")
            .ToArray();
    }

    private static string FormatCandidateList(IReadOnlyList<string> candidates)
    {
        return candidates.Count == 0
            ? "-"
            : string.Join("<br>", candidates);
    }

    private static string FormatDominantManageBonusLayout(IReadOnlyList<PayloadWithFile> payloads)
    {
        if (payloads.Count == 0)
        {
            return "-";
        }

        var group = payloads
            .GroupBy(entry => new
            {
                Byte9Field = PayloadWordAtByteOffset(entry.Payload.PayloadHex, 9),
                Byte11Value = PayloadWordAtByteOffset(entry.Payload.PayloadHex, 11),
                Byte15Value = PayloadWordAtByteOffset(entry.Payload.PayloadHex, 15)
            })
            .OrderByDescending(group => group.Count())
            .ThenBy(group => group.Key.Byte9Field, StringComparer.OrdinalIgnoreCase)
            .First();

        return $"`{group.Key.Byte9Field}` / `{group.Key.Byte11Value}` / `{group.Key.Byte15Value}` ({group.Count()})";
    }

    private static string PayloadWordAtByteOffset(string payloadHex, int byteOffset)
    {
        string[] bytes = payloadHex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        return byteOffset >= 0 && byteOffset + 1 < bytes.Length
            ? $"{bytes[byteOffset]} {bytes[byteOffset + 1]}"
            : "-";
    }

    private static bool IsInteractionAttributeName(string name)
    {
        string[] terms =
        {
            "buy",
            "sell",
            "vendor",
            "shop",
            "merchant",
            "talk",
            "giver",
            "taker",
            "putactive",
            "use",
            "trade",
            "loot",
            "market",
            "inventory",
            "active",
            "interaction",
            "currentstate"
        };

        return terms.Any(term => name.Contains(term, StringComparison.OrdinalIgnoreCase));
    }

    private static IEnumerable<FxMatch> FindFxMatches(string file, ManageBonusPayloadSample payload, IReadOnlyDictionary<string, FxDefinition> fxByHex)
    {
        string[] bytes = payload.PayloadHex.Split(' ', StringSplitOptions.RemoveEmptyEntries);
        for (int offset = 0; offset <= bytes.Length - 4; offset++)
        {
            string hex = string.Concat(bytes.Skip(offset).Take(4)).ToLowerInvariant();
            if (fxByHex.TryGetValue(hex, out FxDefinition? fx))
            {
                yield return new FxMatch(file, payload.Line, offset, hex, fx.Name, payload.PayloadHex);
            }
        }
    }

    private static string FormatList(IReadOnlyList<string> values)
    {
        return values.Count == 0
            ? "`none`"
            : string.Join(", ", values.Select(value => $"`{value}`"));
    }

    private static string FormatSourceLocation(string file, int line)
    {
        return $"{Path.GetFileName(file)}:{line}";
    }

    private static string FormatSequence(IReadOnlyList<string> headers)
    {
        List<string> runs = new();
        for (int i = 0; i < headers.Count;)
        {
            string header = headers[i];
            int count = 1;
            while (i + count < headers.Count && headers[i + count].Equals(header, StringComparison.OrdinalIgnoreCase))
            {
                count++;
            }

            runs.Add(count == 1 ? header : $"{header} x{count}");
            i += count;
        }

        return string.Join(" -> ", runs);
    }

    private static string FormatBoolean(bool value)
    {
        return value ? "yes" : "no";
    }

    private sealed record PacketLocation(string File, int Line);

    private sealed record StateFieldLink(PacketLocation Packet, PlayerAttributePayloadWithFile B2, PayloadWithFile Bc);

    private sealed record LinkedStateValueComparison(
        PacketLocation Packet,
        string B2Field,
        string B2Value,
        string BcByte9Field,
        string BcByte11Value,
        string B2PayloadHex,
        string BcPayloadHex);

    private sealed record ManageBonusLayout(
        string File,
        int Line,
        string Field0,
        string Field1,
        string Field2,
        string Byte9Field,
        string Byte11Value,
        string Byte15Value,
        string PayloadHex);

    private sealed record FxMatch(string File, int Line, int Offset, string Hex, string Name, string PayloadHex);

    private sealed record AttributeCandidateHit(int FieldValue, string IndexKind, AttributeDefinition Attribute);

    private sealed record Protocol04SequenceWithFile(string File, Protocol04PacketSequenceSample Sequence);

    private sealed record Protocol04InteractionWithFile(string File, Protocol04InteractionPayloadSample Payload);

    private sealed record Protocol03SampleWithFile(string File, Protocol03ObjectViewSample Sample);

    private sealed record Protocol03SegmentWithFile(string File, int Line, Protocol03ObjectUpdateSegment Segment);

    private sealed record PlayerAttributePayloadWithFile(string File, PlayerAttributePayloadSample Payload);

    private sealed record PayloadWithFile(string File, ManageBonusPayloadSample Payload);
}
